apiVersion: v1
kind: Namespace
metadata: { name: final }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: { name: mysql-pv-claim, namespace: final }
spec:
  storageClassName: gp2
  accessModes: ["ReadWriteOnce"]
  resources: { requests: { storage: 2Gi } }
