apiVersion: v1
kind: Service
metadata: { name: mysql-service, namespace: final }
spec:
  selector: { app: mysql }
  ports: [{ port: 3306 }]
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata: { name: flask-service, namespace: final }
spec:
  selector: { app: flask-app }
  ports: [{ protocol: TCP, port: 80, targetPort: 81 }]
  type: LoadBalancer
